"""Upgrade-3 single R3->R4 authoring admission verdict (ticket 019).

R4_ADMISSION is generated by ONE function from the hashes of its inputs
(phase3 acceptance, per-section coverage verdicts, claim bindings, handoff):

- the hard-failure predicate checks EVERY required acceptance field; a missing
  field is not ``true``; ``engineering_passed``/``claim_pool_integrity_passed``
  false or ``status=failed`` break the GLOBAL admission;
- per-section: admitted only when the global is healthy AND the 017 coverage
  verdict is scientific_ready; ``needs_more_literature`` admits WITH limits
  (breadth recorded); ``needs_evidence`` blocks with gap notes retained;
- ``partial`` admits the qualified sections only and never grants
  full-manuscript publication permission;
- a handoff whose recorded hash does not match the current inputs is stale and
  blocked (post-hoc state-file edits cannot change permissions);
- legacy phase3 status may be attached as a display projection only.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

ADMISSION_SCHEMA = "optomind.upgrade3.r4_admission.v1"
REQUIRED_ACCEPTANCE_FIELDS = (
    "status", "engineering_passed", "claim_pool_integrity_passed",
    "evidence_permission_passed",
)


def _canonical(value: Any) -> str:
    import json
    return json.dumps(value, sort_keys=True, ensure_ascii=False, default=str)


def _sha(text: str) -> str:
    import hashlib
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def hard_failure_predicate(acceptance: Dict[str, Any]) -> Dict[str, Any]:
    """All-or-nothing engineering check: missing field != true."""
    missing = [k for k in REQUIRED_ACCEPTANCE_FIELDS if k not in acceptance]
    failed_fields = []
    if acceptance.get("engineering_passed") is not True:
        failed_fields.append("engineering_passed")
    if acceptance.get("claim_pool_integrity_passed") is not True:
        failed_fields.append("claim_pool_integrity_passed")
    if acceptance.get("evidence_permission_passed") is not True:
        failed_fields.append("evidence_permission_passed")
    if acceptance.get("status") not in ("passed", "completed_with_limits_ok"):
        failed_fields.append("status:" + str(acceptance.get("status")))
    return {
        "missing_fields": missing,
        "failed_fields": failed_fields,
        "global_broken": bool(missing or failed_fields),
    }


def r4_admission(*, acceptance: Dict[str, Any],
                 section_verdicts: Dict[str, Dict[str, Any]],
                 handoff_hash: str = "",
                 expected_handoff_hash: str = "",
                 acceptance_hash: str = "",
                 bindings_hash: str = "",
                 policy_hash: str = "not_applicable") -> Dict[str, Any]:
    hard = hard_failure_predicate(acceptance)
    global_broken = hard["global_broken"]
    stale_handoff = bool(expected_handoff_hash) and handoff_hash != expected_handoff_hash

    sections: Dict[str, Dict[str, Any]] = {}
    for sid, verdict in section_verdicts.items():
        if stale_handoff:
            sections[sid] = {"admitted": False,
                             "reason": "handoff_stale_hash",
                             "limits": []}
            continue
        if global_broken:
            sections[sid] = {
                "admitted": False,
                "reason": "global_acceptance_broken:" + ",".join(
                    hard["failed_fields"] + hard["missing_fields"]),
                "limits": [],
                "gap_notes_retained": verdict.get("uncovered_required_slots") or [],
            }
            continue
        v_status = verdict.get("status")
        if verdict.get("scientific_ready") is True and v_status == "ready":
            sections[sid] = {"admitted": True, "reason": "load_bearing_ready",
                             "limits": []}
        elif v_status == "needs_more_literature":
            sections[sid] = {"admitted": True,
                             "reason": "scientific_breadth_incomplete",
                             "limits": ["breadth_incomplete",
                                        verdict.get("required_role_coverage", {})
                                        .get("missing", [])]}
        else:
            sections[sid] = {
                "admitted": False,
                "reason": "section_needs_evidence",
                "limits": [],
                "gap_notes_retained": [
                    s.get("slot_id") for s in verdict.get("required_slots", [])
                    if s.get("required") and not s.get("covered")],
            }

    admitted_ids = [s for s, x in sections.items() if x["admitted"]]
    if global_broken or stale_handoff:
        global_status = "blocked"
    elif not admitted_ids:
        global_status = "blocked"
    elif len(admitted_ids) == len(sections) and sections:
        global_status = "full"
    else:
        global_status = "partial"

    full_publication_permission = (
        global_status == "full"
        and all(sections[s].get("limits") == [] for s in admitted_ids)
        and not global_broken)

    admission = {
        "schema_version": ADMISSION_SCHEMA,
        "hard_failure": hard,
        "stale_handoff": stale_handoff,
        "sections": sections,
        "admitted_section_ids": admitted_ids,
        "global_status": global_status,
        "full_publication_permission": full_publication_permission,
        "partial_note": ("partial admits qualified sections only; the "
                         "manuscript as a whole is NOT publication-ready"
                         if global_status == "partial" else None),
        "input_hashes": {
            "acceptance_hash": acceptance_hash,
            "bindings_hash": bindings_hash,
            "handoff_hash": handoff_hash,
            "expected_handoff_hash": expected_handoff_hash,
        },
        "policy_hash": policy_hash,
        "legacy_phase3_display": {
            "legacy_status_display": acceptance.get("status"),
            "authority": "projection_only",
        },
        "admission_hash": _sha(_canonical({
            "sections": sections, "global_status": global_status,
            "acceptance_hash": acceptance_hash, "bindings_hash": bindings_hash})),
    }
    return admission


def worker_gate(admission: Dict[str, Any], section_id: str) -> Dict[str, Any]:
    """Re-verified by the real worker BEFORE building its packet: a blocked
    section must cause ZERO downstream calls."""
    sec = admission["sections"].get(section_id)
    if not sec:
        return {"allow": False, "reason": "section_not_in_admission"}
    if admission["global_status"] == "blocked":
        return {"allow": False, "reason": sec["reason"]}
    if not sec["admitted"]:
        return {"allow": False, "reason": sec["reason"],
                "gap_notes": sec.get("gap_notes_retained", [])}
    return {"allow": True, "limits": sec["limits"]}
