"""Run-level observability for the reusable OptoMind Research Harness.

Leaf ResearchWorker tasks already write detailed ``EVENTS.jsonl`` and
``COST.json`` files.  This module adds the missing run-level layer:

* one append-only lifecycle timeline;
* authoritative total and per-stage time/token/CNY metrics;
* an index of every active leaf log, error, recovery and tool/model call;
* a compact human-readable operations report.

The reports are generated by the system itself.  They are intentionally
content-light and secret-safe so they can later be consumed by monitoring or
self-improvement agents without exposing API keys or full model responses.
"""

from __future__ import annotations

import json
import os
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable

from .artifact_store import append_jsonl, atomic_write_json, atomic_write_text
from .event_logger import _redact


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _read_json(path: Path) -> Dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}
    except Exception:
        return {}


def _read_utf8_lines(path: Path) -> tuple[list[str], int]:
    """Read JSONL lines as UTF-8 without silently repairing invalid bytes.

    A malformed line must not prevent terminal reconciliation of the remaining
    log.  Decode each physical line strictly when the whole file is not valid
    UTF-8 and count the lines that cannot be decoded.
    """

    try:
        return path.read_text(encoding="utf-8").splitlines(), 0
    except UnicodeDecodeError:
        lines: list[str] = []
        malformed = 0
        try:
            raw_lines = path.read_bytes().splitlines()
        except OSError:
            return [], 0
        for raw_line in raw_lines:
            try:
                lines.append(raw_line.decode("utf-8"))
            except UnicodeDecodeError:
                malformed += 1
        return lines, malformed
    except OSError:
        return [], 0


def _stage_cost_cny(value: Dict[str, Any]) -> float:
    """Read one canonical numeric CNY field without summing aliases."""

    for key in ("cost_cny", "estimated_cost_cny", "total_cost_cny"):
        if value.get(key) is not None:
            try:
                return float(value.get(key) or 0.0)
            except (TypeError, ValueError):
                return 0.0
    return 0.0


def _stage_tokens(value: Dict[str, Any], key: str) -> int:
    for candidate in (key, f"total_{key}"):
        if value.get(candidate) is not None:
            try:
                return int(value.get(candidate) or 0)
            except (TypeError, ValueError):
                return 0
    return 0


def _explicit_model_call_count(value: Dict[str, Any]) -> int | None:
    for key in ("model_call_count", "model_calls", "call_count"):
        if value.get(key) is not None:
            try:
                return max(0, int(value.get(key) or 0))
            except (TypeError, ValueError):
                return 0
    return None


def _inferred_query_planner_call_count(value: Dict[str, Any]) -> int:
    explicit = _explicit_model_call_count(value)
    if explicit is not None:
        return explicit
    status = str(value.get("status") or "")
    if status in {
        "provided_confirmed_plan",
        "reused_confirmed_query_plan",
    }:
        return 0
    if status in {
        "repaired_by_format_model",
        "deterministic_fallback_after_repair_failed",
    }:
        return 2
    return int(
        _stage_tokens(value, "input_tokens") > 0
        or _stage_tokens(value, "output_tokens") > 0
        or _stage_cost_cny(value) > 0
    )


def _truthful_stage(value: Any, fallback: str = "orchestrator") -> str:
    stage = str(value or "").strip()
    return fallback if stage in {"", "initializing"} else stage


def _active_files(root: Path, names: set[str]) -> Iterable[Path]:
    """Yield runtime artifacts without following links or unrelated history."""

    excluded = {
        ".git",
        ".history",
        "__pycache__",
    }
    if not root.exists():
        return
    for current, dirs, files in os.walk(
        str(root),
        topdown=True,
        onerror=lambda _error: None,
        followlinks=False,
    ):
        dirs[:] = [name for name in dirs if name not in excluded]
        for name in files:
            if name in names:
                yield Path(current) / name


def _stage_from_relative_path(relative: Path) -> str:
    if not relative.parts:
        return "run"
    first = relative.parts[0]
    aliases = {
        "authoring": "authoring_revision",
        "research_program": "research_plan",
        "query_planner": "query_planner",
        "review_lead": "review_lead",
        "section_coverage": "section_coverage",
        "visual_editor": "visual_editor",
    }
    return aliases.get(first, first)


class HarnessObservability:
    """Own the run timeline and derive durable operational reports."""

    def __init__(self, work_dir: Path, run_id: str) -> None:
        self.work_dir = Path(work_dir)
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.run_id = run_id
        self.events_path = self.work_dir / "HARNESS_EVENTS.jsonl"
        self.metrics_path = self.work_dir / "HARNESS_METRICS.json"
        self.log_index_path = self.work_dir / "HARNESS_LOG_INDEX.json"
        self.report_path = self.work_dir / "HARNESS_RUN_REPORT.md"
        self._invocation_t0: float | None = None
        # ``active_wall_time_seconds`` measures work performed by the
        # harness, not the time spent writing the harness's own checkpoints.
        # Keep the latter in memory for the current invocation so repeated
        # live snapshots do not make the next snapshot appear to have done
        # extra work merely because the previous snapshot was slow to save.
        self._excluded_observability_seconds = 0.0
        self._stage_t0: Dict[str, float] = {}

    def emit(self, event: str, **details: Any) -> None:
        record = {
            "timestamp": _now(),
            "run_id": self.run_id,
            "event": event,
            **details,
        }
        append_jsonl(self.events_path, _redact(record))

    def start_run(self, *, entry_mode: str, resumed: bool = False) -> None:
        if self._invocation_t0 is not None:
            return
        self._invocation_t0 = time.monotonic()
        self._excluded_observability_seconds = 0.0
        self.emit(
            "run_resumed" if resumed else "run_started",
            entry_mode=entry_mode,
        )

    def _current_invocation_elapsed(self, now: float | None = None) -> float:
        """Return active time for this invocation, excluding prior snapshots.

        Snapshot persistence is bookkeeping performed by this observer.  It
        must not inflate the work duration reported by a later snapshot or by
        the final ``run_finished`` event.  The exclusion is process-local;
        only a final snapshot commits the invocation total, preserving the
        existing resume semantics for an unfinished invocation.
        """

        if self._invocation_t0 is None:
            return 0.0
        current = time.monotonic() if now is None else now
        return max(
            0.0,
            current
            - self._invocation_t0
            - self._excluded_observability_seconds,
        )

    def start_stage(self, stage: str, **details: Any) -> None:
        if stage in self._stage_t0:
            return
        self._stage_t0[stage] = time.monotonic()
        self.emit("stage_started", stage=stage, **details)

    def finish_stage(
        self,
        stage: str,
        status: str,
        *,
        estimated_cost_cny: float = 0.0,
        cost_cny: float | None = None,
        input_tokens: int = 0,
        output_tokens: int = 0,
        wall_time_seconds: float | None = None,
        **details: Any,
    ) -> float:
        """Close a stage, distinguishing an unmeasured stage from an instant one.

        A stage finished without a matching ``start_stage`` used to report
        ``wall_time_seconds: 0.0``, which is indistinguishable from a stage that
        genuinely took no time.  Verified on rhr_be780761:
        ``publication_mainline_commander`` billed 0.600954 CNY over 955,104
        input tokens and ``publication_mainline_staged_completion`` billed
        0.661369 CNY over 525,857 tokens, yet both ledgers recorded 0.0 -- paid
        work whose duration silently vanished from the displayed total.

        Callers that know a duration out-of-band may pass ``wall_time_seconds``.
        When neither a start timestamp nor an explicit duration exists, the
        emitted event carries ``wall_time_measured: false`` so a reader can tell
        "never timed" from "took no time" instead of guessing.
        """

        started = self._stage_t0.pop(stage, None)
        if started is not None:
            duration = max(0.0, time.monotonic() - started)
            measured = True
        elif wall_time_seconds is not None:
            duration = max(0.0, float(wall_time_seconds))
            measured = True
        else:
            duration = 0.0
            measured = False
        reported_cost_cny = (
            float(estimated_cost_cny)
            if cost_cny is None
            else float(cost_cny)
        )
        self.emit(
            "stage_finished",
            stage=stage,
            status=status,
            wall_time_seconds=round(duration, 3),
            wall_time_measured=measured,
            cost_cny=round(reported_cost_cny, 6),
            estimated_cost_cny=round(reported_cost_cny, 6),
            input_tokens=int(input_tokens),
            output_tokens=int(output_tokens),
            **details,
        )
        return duration

    def mark_stage_reused(self, stage: str, **details: Any) -> None:
        self.finish_stage(stage, "completed", reused=True, **details)

    def fail(self, *, stage: str, error_type: str, detail: str) -> None:
        self.emit(
            "run_error",
            stage=stage,
            error_type=error_type,
            detail=str(detail)[:1000],
        )

    def _root_events(self) -> list[Dict[str, Any]]:
        events: list[Dict[str, Any]] = []
        if not self.events_path.exists():
            return events
        lines, _malformed_utf8 = _read_utf8_lines(self.events_path)
        for line in lines:
            try:
                value = json.loads(line)
            except Exception:
                continue
            if isinstance(value, dict):
                events.append(value)
        return events

    def _build_log_index(self) -> Dict[str, Any]:
        event_files = sorted(
            _active_files(self.work_dir, {"EVENTS.jsonl"}),
            key=lambda path: str(path).lower(),
        )
        entries: list[Dict[str, Any]] = []
        aggregate_events: Counter[str] = Counter()
        aggregate_models: Counter[str] = Counter()
        aggregate_tools: Counter[str] = Counter()
        stage_model_calls: Counter[str] = Counter()
        tool_starts: Dict[tuple[str, str], list[Dict[str, Any]]] = defaultdict(list)
        tool_results: Dict[tuple[str, str], list[Dict[str, Any]]] = defaultdict(list)
        tool_interruptions: Dict[tuple[str, str], Dict[str, Any]] = {}
        unkeyed_tool_starts: list[Dict[str, Any]] = []
        unkeyed_tool_results: list[Dict[str, Any]] = []
        unkeyed_tool_interruptions: list[Dict[str, Any]] = []
        file_tool_counts: Dict[str, Counter[str]] = defaultdict(Counter)
        errors: list[Dict[str, Any]] = []
        recoveries: list[Dict[str, Any]] = []

        for path in event_files:
            relative = path.relative_to(self.work_dir)
            relative_path = relative.as_posix()
            stage_name = _stage_from_relative_path(relative)
            event_counts: Counter[str] = Counter()
            model_counts: Counter[str] = Counter()
            tool_counts: Counter[str] = Counter()
            first_timestamp = ""
            last_timestamp = ""
            line_count = 0
            lines, malformed_utf8_lines = _read_utf8_lines(path)
            malformed_lines = malformed_utf8_lines
            for line_number, line in enumerate(lines, 1):
                if not line.strip():
                    continue
                line_count += 1
                try:
                    event = json.loads(line)
                except Exception:
                    malformed_lines += 1
                    continue
                if not isinstance(event, dict):
                    malformed_lines += 1
                    continue
                event_name = str(event.get("event") or "unknown")
                event_counts[event_name] += 1
                aggregate_events[event_name] += 1
                timestamp = str(
                    event.get("timestamp")
                    or event.get("created_at")
                    or ""
                )
                if timestamp:
                    first_timestamp = first_timestamp or timestamp
                    last_timestamp = timestamp
                model = str(event.get("model") or "")
                if model and event_name in {
                    "model_call_start",
                    "model_call_end",
                    "model_switch",
                    "recovery",
                }:
                    model_counts[model] += 1
                    aggregate_models[model] += 1
                if event_name == "model_call_end":
                    stage_model_calls[stage_name] += 1
                tool = str(event.get("tool") or "")
                if tool:
                    tool_counts[tool] += 1
                    aggregate_tools[tool] += 1
                if event_name in {
                    "tool_call",
                    "tool_result",
                    "tool_call_interrupted",
                }:
                    call_id = str(event.get("call_id") or "").strip()
                    ref = {
                        "stage": stage_name,
                        "log_path": str(path),
                        "relative_path": relative_path,
                        "line_number": line_number,
                        "call_id": call_id,
                        "tool": tool,
                        "event": event_name,
                    }
                    stable_call_id = call_id not in {"", "?", "unknown"}
                    if event_name == "tool_call":
                        file_tool_counts[relative_path]["start_count"] += 1
                        if stable_call_id:
                            tool_starts[(relative_path, call_id)].append(ref)
                        else:
                            unkeyed_tool_starts.append(ref)
                    elif event_name == "tool_result":
                        file_tool_counts[relative_path]["result_count"] += 1
                        if stable_call_id:
                            tool_results[(relative_path, call_id)].append(ref)
                        else:
                            unkeyed_tool_results.append(ref)
                    else:
                        if stable_call_id:
                            tool_interruptions[(relative_path, call_id)] = ref
                        else:
                            unkeyed_tool_interruptions.append(ref)
                if event_name == "error":
                    errors.append(
                        {
                            "stage": stage_name,
                            "log_path": str(path),
                            "error_type": str(
                                event.get("error_type") or "unknown"
                            ),
                            "detail": str(event.get("detail") or "")[:500],
                        }
                    )
                elif event_name in {"recovery", "model_switch"}:
                    recoveries.append(
                        {
                            "stage": stage_name,
                            "log_path": str(path),
                            "event": event_name,
                            "from_model": str(
                                event.get("from_model")
                                or event.get("from")
                                or ""
                            ),
                            "to_model": str(
                                event.get("to_model")
                                or event.get("to")
                                or ""
                            ),
                            "reason": str(event.get("reason") or "")[:300],
                        }
                    )
            entries.append(
                {
                    "stage": _stage_from_relative_path(relative),
                    "archived_attempt": any(
                        part in {"_runtime_archive", "runtime_archive"}
                        for part in relative.parts
                    ),
                    "path": str(path),
                    "relative_path": relative.as_posix(),
                    "line_count": line_count,
                    "malformed_line_count": malformed_lines,
                    "file_size_bytes": path.stat().st_size,
                    "first_timestamp": first_timestamp,
                    "last_timestamp": last_timestamp,
                    "event_counts": dict(sorted(event_counts.items())),
                    "model_event_counts": dict(sorted(model_counts.items())),
                    "tool_call_counts": dict(sorted(tool_counts.items())),
                    "tool_call_start_count": int(
                        file_tool_counts[relative_path]["start_count"]
                    ),
                    "tool_result_count": int(
                        file_tool_counts[relative_path]["result_count"]
                    ),
                }
            )

        tool_pairs: list[Dict[str, Any]] = []
        orphan_events: list[Dict[str, Any]] = []
        duplicate_start_count = 0
        duplicate_result_count = 0
        paired_count = 0
        interrupted_count = 0
        orphan_result_count = 0

        for key in sorted(
            set(tool_starts) | set(tool_results),
            key=lambda value: (value[0], value[1]),
        ):
            starts = tool_starts.get(key, [])
            results = tool_results.get(key, [])
            duplicate_start_count += max(0, len(starts) - 1)
            duplicate_result_count += max(0, len(results) - 1)
            pair_count = min(len(starts), len(results))
            for index in range(pair_count):
                start = starts[index]
                result = results[index]
                pair_status = (
                    "paired"
                    if start["tool"] == result["tool"]
                    else "paired_tool_name_mismatch"
                )
                tool_pairs.append(
                    {
                        "stage": start["stage"],
                        "log_path": start["log_path"],
                        "call_id": key[1],
                        "tool_start": start["tool"],
                        "tool_result": result["tool"],
                        "start_line": start["line_number"],
                        "result_line": result["line_number"],
                        "pairing_status": pair_status,
                    }
                )
                paired_count += 1
            interruption_marker = tool_interruptions.get(key)
            for start in starts[pair_count:]:
                interrupted_count += 1
                orphan_events.append(
                    {
                        **start,
                        "pairing_status": "interrupted",
                        "reason": "missing_tool_result",
                        "interruption_line": (
                            interruption_marker["line_number"]
                            if interruption_marker
                            else None
                        ),
                    }
                )
            for result in results[pair_count:]:
                orphan_result_count += 1
                orphan_events.append(
                    {
                        **result,
                        "pairing_status": "orphan_result",
                        "reason": "missing_tool_start",
                    }
                )
            if interruption_marker and not starts[pair_count:]:
                orphan_events.append(
                    {
                        **interruption_marker,
                        "pairing_status": "orphan_interruption_marker",
                        "reason": "missing_tool_start",
                    }
                )

        for start in unkeyed_tool_starts:
            interrupted_count += 1
            orphan_events.append(
                {
                    **start,
                    "pairing_status": "unkeyed_start",
                    "reason": "missing_stable_call_id",
                }
            )
        for result in unkeyed_tool_results:
            orphan_result_count += 1
            orphan_events.append(
                {
                    **result,
                    "pairing_status": "unkeyed_result",
                    "reason": "missing_stable_call_id",
                }
            )
        for marker in unkeyed_tool_interruptions:
            orphan_events.append(
                {
                    **marker,
                    "pairing_status": "unkeyed_interruption_marker",
                    "reason": "missing_stable_call_id",
                }
            )

        orphan_events.sort(
            key=lambda value: (
                str(value.get("relative_path") or ""),
                int(value.get("line_number", 0) or 0),
            )
        )
        tool_start_count = int(aggregate_events.get("tool_call", 0))
        tool_result_count = int(aggregate_events.get("tool_result", 0))
        tool_reconciliation = {
            "start_count": tool_start_count,
            "result_count": tool_result_count,
            "paired_count": paired_count,
            "canonical_call_count": paired_count + interrupted_count,
            "interrupted_count": interrupted_count,
            "orphan_result_count": orphan_result_count,
            "duplicate_start_count": duplicate_start_count,
            "duplicate_result_count": duplicate_result_count,
            "stable_call_id_required": True,
            "balanced": (
                tool_start_count == tool_result_count
                and not orphan_events
            ),
            "pairs": tool_pairs,
            "orphan_events": orphan_events,
        }

        result_files = list(
            _active_files(
                self.work_dir,
                {"RESULT.json", "COST.json", "AGENT_STATE.json"},
            )
        )
        for path in result_files:
            if path.name != "RESULT.json":
                continue
            value = _read_json(path)
            relative = path.relative_to(self.work_dir)
            for detail in value.get("errors", []):
                errors.append(
                    {
                        "stage": _stage_from_relative_path(relative),
                        "log_path": str(path),
                        "error_type": "worker_result_error",
                        "detail": str(detail)[:500],
                        "archived_attempt": any(
                            part in {"_runtime_archive", "runtime_archive"}
                            for part in relative.parts
                        ),
                    }
                )
        return {
            "schema_version": "research_harness.log_index.v1",
            "run_id": self.run_id,
            "generated_at": _now(),
            "event_log_count": len(entries),
            "event_logs": entries,
            "aggregate_event_counts": dict(sorted(aggregate_events.items())),
            "aggregate_model_event_counts": dict(
                sorted(aggregate_models.items())
            ),
            "aggregate_tool_call_counts": dict(
                sorted(aggregate_tools.items())
            ),
            "stage_model_call_counts": dict(sorted(stage_model_calls.items())),
            "model_call_start_count": int(
                aggregate_events.get("model_call_start", 0)
            ),
            "model_call_end_count": int(
                aggregate_events.get("model_call_end", 0)
            ),
            "tool_call_reconciliation": tool_reconciliation,
            "errors": errors,
            "recoveries": recoveries,
            "runtime_artifact_paths": sorted(str(path) for path in result_files),
        }

    def _stage_durations(self) -> Dict[str, Dict[str, Any]]:
        active: Dict[str, list[Dict[str, Any]]] = defaultdict(list)
        durations: Dict[str, float] = defaultdict(float)
        attempts: Counter[str] = Counter()
        last_status: Dict[str, str] = {}
        reused: Counter[str] = Counter()
        for event in self._root_events():
            stage = str(event.get("stage") or "")
            if not stage:
                continue
            if event.get("event") == "stage_started":
                active[stage].append(event)
            elif event.get("event") == "stage_finished":
                attempts[stage] += 1
                durations[stage] += max(
                    0.0, float(event.get("wall_time_seconds", 0.0) or 0.0)
                )
                last_status[stage] = str(event.get("status") or "")
                if event.get("reused"):
                    reused[stage] += 1
                if active[stage]:
                    active[stage].pop()
        all_stages = sorted(set(durations) | set(active) | set(last_status))
        return {
            stage: {
                "wall_time_seconds": round(durations[stage], 3),
                "attempt_count": int(attempts[stage]),
                "unfinished_attempt_count": len(active[stage]),
                "reused_attempt_count": int(reused[stage]),
                "last_status": last_status.get(stage, ""),
            }
            for stage in all_stages
        }

    def snapshot(
        self,
        *,
        status: str,
        current_stage: str,
        stage_costs: Dict[str, Dict[str, Any]],
        harness_state: Dict[str, Any],
        final: bool = False,
    ) -> Dict[str, Any]:
        status = str(status or "failed")
        current_stage = _truthful_stage(
            current_stage or harness_state.get("current_stage")
        )
        # Capture the elapsed active time before doing any work required to
        # materialize this snapshot.  Otherwise log-index construction and
        # atomic writes become part of the next live duration measurement.
        snapshot_started = time.monotonic()
        log_index = self._build_log_index()
        atomic_write_json(self.log_index_path, log_index)
        prior = _read_json(self.metrics_path)
        prior_active = float(
            prior.get("committed_active_wall_time_seconds", 0.0) or 0.0
        )
        invocation_elapsed = self._current_invocation_elapsed(
            snapshot_started
        )
        # A final snapshot is taken once per process invocation.  Intermediate
        # snapshots expose live elapsed time but do not permanently accumulate
        # it, which prevents double counting on resume.
        active_total = prior_active + invocation_elapsed
        stage_timings = self._stage_durations()
        canonical_stage_costs: Dict[str, Dict[str, Any]] = {
            str(stage): dict(value)
            for stage, value in stage_costs.items()
            if isinstance(value, dict)
        }
        planner_artifact = _read_json(
            self.work_dir / "query_planner" / "QUERY_PLANNER_COST.json"
        )
        if planner_artifact:
            planner_stage = dict(
                canonical_stage_costs.get("query_planner", {})
            )
            merged_planner = dict(planner_artifact)
            merged_planner.update(planner_stage)
            merged_cost = round(
                max(
                    _stage_cost_cny(planner_stage),
                    _stage_cost_cny(planner_artifact),
                ),
                6,
            )
            merged_planner["cost_cny"] = merged_cost
            merged_planner["estimated_cost_cny"] = merged_cost
            merged_planner["input_tokens"] = max(
                _stage_tokens(planner_stage, "input_tokens"),
                _stage_tokens(planner_artifact, "input_tokens"),
            )
            merged_planner["output_tokens"] = max(
                _stage_tokens(planner_stage, "output_tokens"),
                _stage_tokens(planner_artifact, "output_tokens"),
            )
            stage_count = _explicit_model_call_count(planner_stage)
            artifact_count = _explicit_model_call_count(planner_artifact)
            if stage_count is not None or artifact_count is not None:
                merged_planner["model_call_count"] = max(
                    stage_count or 0,
                    artifact_count or 0,
                )
            canonical_stage_costs["query_planner"] = merged_planner
        logged_stage_model_calls = {
            str(stage): int(count or 0)
            for stage, count in (
                log_index.get("stage_model_call_counts", {}) or {}
            ).items()
        }
        stage_names = (
            set(canonical_stage_costs)
            | set(stage_timings)
            | set(harness_state.get("stages", {}))
            | set(logged_stage_model_calls)
            | {
                str(stage)
                for stage in harness_state.get("canonical_stages", [])
                if str(stage).strip()
            }
        )
        canonical_stage_model_calls: Dict[str, int] = {}
        for stage in sorted(stage_names):
            value = canonical_stage_costs.get(stage, {})
            if not isinstance(value, dict):
                value = {}
            explicit_count = _explicit_model_call_count(value)
            if explicit_count is None and stage == "query_planner":
                explicit_count = _inferred_query_planner_call_count(
                    planner_artifact or value
                )
            canonical_stage_model_calls[stage] = max(
                logged_stage_model_calls.get(stage, 0),
                explicit_count if explicit_count is not None else 0,
            )
        total_input = sum(
            _stage_tokens(value, "input_tokens")
            for value in canonical_stage_costs.values()
            if isinstance(value, dict)
        )
        total_output = sum(
            _stage_tokens(value, "output_tokens")
            for value in canonical_stage_costs.values()
            if isinstance(value, dict)
        )
        total_cost = round(
            sum(
                _stage_cost_cny(value)
                for value in canonical_stage_costs.values()
                if isinstance(value, dict)
            ),
            6,
        )
        stage_metrics: Dict[str, Dict[str, Any]] = {}
        for stage in sorted(stage_names):
            value = canonical_stage_costs.get(stage, {})
            if not isinstance(value, dict):
                value = {}
            stage_cost = round(_stage_cost_cny(value), 6)
            stage_metrics[stage] = {
                **stage_timings.get(
                    stage,
                    {
                        "wall_time_seconds": 0.0,
                        "attempt_count": 0,
                        "unfinished_attempt_count": 0,
                        "reused_attempt_count": 0,
                        "last_status": "",
                    },
                ),
                "status": str(
                    harness_state.get("stages", {})
                    .get(stage, {})
                    .get("status")
                    or value.get("status")
                    or stage_timings.get(stage, {}).get("last_status")
                    or ""
                ),
                "model_call_count": canonical_stage_model_calls.get(
                    stage, 0
                ),
                "input_tokens": _stage_tokens(value, "input_tokens"),
                "output_tokens": _stage_tokens(value, "output_tokens"),
                "cost_cny": stage_cost,
                "estimated_cost_cny": stage_cost,
            }
        tool_reconciliation = dict(
            log_index.get("tool_call_reconciliation", {}) or {}
        )
        canonical_model_call_count = sum(
            canonical_stage_model_calls.values()
        )
        canonical_tool_call_count = int(
            tool_reconciliation.get("canonical_call_count", 0) or 0
        )
        metrics = {
            "schema_version": "research_harness.metrics.v1",
            "run_id": self.run_id,
            "status": status,
            "current_stage": current_stage,
            "completed_stage": current_stage if final else "",
            "started_at": str(
                prior.get("started_at")
                or harness_state.get("created_at")
                or _now()
            ),
            "completed_at": _now() if final else "",
            "active_wall_time_seconds": round(active_total, 3),
            "committed_active_wall_time_seconds": round(
                active_total if final else prior_active,
                3,
            ),
            "current_invocation_wall_time_seconds": round(
                invocation_elapsed, 3
            ),
            "total_input_tokens": total_input,
            "total_output_tokens": total_output,
            "total_tokens": total_input + total_output,
            "cost_cny": total_cost,
            "estimated_cost_cny": total_cost,
            "billing_currency": "CNY",
            "canonical_totals": {
                "model_calls": canonical_model_call_count,
                "tool_calls": canonical_tool_call_count,
                "input_tokens": total_input,
                "output_tokens": total_output,
                "total_tokens": total_input + total_output,
                "cost_cny": total_cost,
                "billing_currency": "CNY",
                "stages": sorted(stage_names),
            },
            "stage_metrics": stage_metrics,
            "operations": {
                "event_log_count": log_index["event_log_count"],
                "model_call_count": canonical_model_call_count,
                "model_call_start_count": int(
                    log_index.get("model_call_start_count", 0) or 0
                ),
                "model_call_end_count": int(
                    log_index.get("model_call_end_count", 0) or 0
                ),
                "tool_call_count": canonical_tool_call_count,
                "tool_call_start_count": int(
                    tool_reconciliation.get("start_count", 0) or 0
                ),
                "tool_result_count": int(
                    tool_reconciliation.get("result_count", 0) or 0
                ),
                "tool_call_paired_count": int(
                    tool_reconciliation.get("paired_count", 0) or 0
                ),
                "tool_call_interrupted_count": int(
                    tool_reconciliation.get("interrupted_count", 0) or 0
                ),
                "tool_call_orphan_result_count": int(
                    tool_reconciliation.get("orphan_result_count", 0) or 0
                ),
                "tool_call_reconciliation_balanced": bool(
                    tool_reconciliation.get("balanced", True)
                ),
                "error_count": len(log_index["errors"]),
                "recovery_count": len(log_index["recoveries"]),
                "malformed_log_line_count": sum(
                    int(item["malformed_line_count"])
                    for item in log_index["event_logs"]
                ),
            },
            "artifacts": {
                "timeline": str(self.events_path),
                "log_index": str(self.log_index_path),
                "human_report": str(self.report_path),
            },
            "tool_call_reconciliation": tool_reconciliation,
            "generated_at": _now(),
        }
        atomic_write_json(self.metrics_path, metrics)
        self._write_markdown_report(metrics, log_index)
        if final:
            self._invocation_t0 = None
            self._excluded_observability_seconds = 0.0
        elif self._invocation_t0 is not None:
            # Exclude this completed persistence interval from every future
            # snapshot in the same invocation.  The active value itself is
            # still computed from the original invocation start, so no work
            # interval is reset or double-counted.
            self._excluded_observability_seconds += max(
                0.0, time.monotonic() - snapshot_started
            )
        return metrics

    def _write_markdown_report(
        self,
        metrics: Dict[str, Any],
        log_index: Dict[str, Any],
    ) -> None:
        lines = [
            "# OptoMind Research Harness Run Report",
            "",
            f"- Run ID: `{self.run_id}`",
            f"- Status: `{metrics['status']}`",
            f"- Current stage: `{metrics['current_stage']}`",
            (
                "- Active wall time: "
                f"{metrics['active_wall_time_seconds']:.2f} seconds"
            ),
            (
                "- Tokens: "
                f"{metrics['total_input_tokens']:,} input + "
                f"{metrics['total_output_tokens']:,} output"
            ),
            (
                "- Estimated model cost: "
                f"CNY {metrics['cost_cny']:.4f}"
            ),
            "",
            "## Stage metrics",
            "",
            "| Stage | Status | Seconds | Input tokens | Output tokens | Cost (CNY) |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        for stage, value in metrics["stage_metrics"].items():
            lines.append(
                f"| {stage} | {value['status']} | "
                f"{value['wall_time_seconds']:.2f} | "
                f"{value['input_tokens']:,} | "
                f"{value['output_tokens']:,} | "
                f"{value['estimated_cost_cny']:.4f} |"
            )
        operations = metrics["operations"]
        lines.extend(
            [
                "",
                "## Operational trace",
                "",
                f"- Indexed event logs: {operations['event_log_count']}",
                f"- Completed model calls: {operations['model_call_count']}",
                (
                    "- Tool calls: "
                    f"{operations['tool_call_count']} canonical / "
                    f"{operations['tool_result_count']} results"
                ),
                (
                    "- Tool reconciliation: "
                    f"{operations['tool_call_interrupted_count']} interrupted, "
                    f"{operations['tool_call_orphan_result_count']} orphan results"
                ),
                f"- Errors: {operations['error_count']}",
                f"- Recoveries/model switches: {operations['recovery_count']}",
                (
                    "- Detailed machine-readable log index: "
                    f"`{self.log_index_path}`"
                ),
            ]
        )
        if log_index["errors"]:
            lines.extend(["", "## Recorded errors", ""])
            for item in log_index["errors"][:20]:
                lines.append(
                    f"- `{item['stage']}` / `{item['error_type']}`: "
                    f"{item['detail']}"
                )
        atomic_write_text(self.report_path, "\n".join(lines) + "\n")

    def finish_run(
        self,
        *,
        status: str,
        current_stage: str,
        stage_costs: Dict[str, Dict[str, Any]],
        harness_state: Dict[str, Any],
    ) -> Dict[str, Any]:
        current_stage = _truthful_stage(
            current_stage or harness_state.get("current_stage")
        )
        duration = self._current_invocation_elapsed()
        self.emit(
            "run_finished",
            status=status,
            current_stage=current_stage,
            completed_stage=current_stage,
            invocation_wall_time_seconds=round(duration, 3),
        )
        return self.snapshot(
            status=status,
            current_stage=current_stage,
            stage_costs=stage_costs,
            harness_state=harness_state,
            final=True,
        )
