"""Narrow bridge from the latest staged complete manuscript to the planner.

This module is the ``visualhandoff`` bridge between the staged full-manuscript
work order (``Abstract``, ``Introduction``, ``S01``..``S08``, ``Conclusion``)
and the existing deterministic article visual asset planner / visual evidence
factory pipeline.

Responsibilities:

* Parse the staged Markdown into the canonical section order using exact
  headings; duplicate/missing/out-of-order section ids are rejected with
  clear errors.
* Enrich each section with commander responsibilities/theses (and, when
  provided, the staged global inputs) so the existing planner receives rich
  section inputs without rewriting manuscript prose.
* Load the existing long-term visual cache snapshot through the existing
  planner adapter and rerun the existing semantic/diversity/permission
  planning unchanged.
* Allow 0-2 placements per section and record empty/weak coverage instead of
  forcing a figure.
* Preserve permission and publication-eligibility fields and exclude weak
  cross-domain candidates using the planner's existing hard exclusions (no
  new brittle threshold is introduced).
* Produce deterministic remount inputs, plan, review queue, factory-ready
  plan reference, and remount audit without modifying source caches or old
  plans.  No images are generated by this bridge.

The bridge is local-first: every input is a local file or directory, no
network/model calls are made, and all outputs are written into the caller
supplied ``output_dir``.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

from .article_visual_asset_planner import (
    ArticleVisualAssetPlannerConfig,
    to_visual_editorial_plan,
)
from .artifact_store import atomic_write_json
from .visual_asset_planner_adapter import (
    load_visual_cache_records,
    run_article_visual_asset_planner,
)
from .visual_evidence_factory import (
    apply_structural_visual_policy,
)


SCHEMA_VERSION = "optomind.staged_visual_remount.v1"

# Exact canonical order used by the staged manuscript assembler.
STAGED_SECTION_IDS = (
    "Abstract",
    "Introduction",
    "S01",
    "S02",
    "S03",
    "S04",
    "S05",
    "S06",
    "S07",
    "S08",
    "Conclusion",
)

PLANNER_SUBDIR = "planner"
ARTIFACT_INPUTS = "STAGED_VISUAL_REMOUNT_INPUTS.json"
ARTIFACT_PLAN = "STAGED_VISUAL_REMOUNT_PLAN.json"
ARTIFACT_REVIEW_QUEUE = "STAGED_VISUAL_REMOUNT_REVIEW_QUEUE.json"
ARTIFACT_FACTORY_PLAN = "STAGED_VISUAL_REMOUNT_FACTORY_PLAN.json"
ARTIFACT_AUDIT = "STAGED_VISUAL_REMOUNT_AUDIT.json"
ARTIFACT_BLUEPRINT = "STAGED_VISUAL_REMOUNT_BLUEPRINT.json"

_HEADING_RE = re.compile(r"^(?P<level>#{1,6})\s+(?P<title>.+?)\s*$")
_REF_MARKER_RE = re.compile(r"\[REF:([^\]]+)\]")
_SECTION_ID_RE = re.compile(r"\b(S\d{2,})\b", re.IGNORECASE)


class StagedVisualRemountError(ValueError):
    """Raised for contract/programmer errors, never for missing visuals."""


def _canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
    )


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_json(value: Any) -> str:
    return hashlib.sha256(
        _canonical_json(value).encode("utf-8")
    ).hexdigest()


def _normalize_heading(title: str) -> str:
    return re.sub(r"\s+", " ", str(title or "")).strip()


def _heading_explicit_id(title: str) -> Optional[str]:
    """Return a canonical section id explicitly named in a heading, if any.

    Only exact names (``Abstract``, ``Introduction``, ``Conclusion``) or an
    ``S0N`` token are recognized so ordinary section titles such as
    "Foundations of ..." never trigger false id detection.
    """

    normalized = _normalize_heading(title)
    folded = normalized.casefold()
    if folded in {"abstract", "introduction", "conclusion"}:
        return {
            "abstract": "Abstract",
            "introduction": "Introduction",
            "conclusion": "Conclusion",
        }[folded]
    match = _SECTION_ID_RE.search(normalized)
    if match:
        return match.group(1).upper()
    return None


def _citation_ids_from_text(text: str) -> list[str]:
    """Extract deduplicated ``[REF:...]`` citation identities in order."""

    seen: set[str] = set()
    ids: list[str] = []
    for raw in _REF_MARKER_RE.findall(str(text or "")):
        identity = " ".join(str(raw).split())
        if identity and identity not in seen:
            seen.add(identity)
            ids.append(identity)
    return ids


def parse_staged_manuscript(
    markdown: str,
    *,
    allow_dynamic_sections: bool = False,
) -> dict[str, Any]:
    """Parse staged Markdown into canonical sections in exact order.

    The default parser accepts the historical ``Abstract``, ``Introduction``,
    ``S01``..``S08``, and ``Conclusion`` contract. Production remounts may set
    ``allow_dynamic_sections`` so the middle section IDs are read from the
    actual manuscript (for example S01..S07,S09); missing visuals never force
    a synthetic section. Consecutive headings with the same title are treated
    as a TOC duplicate of one section heading. Any duplicate, missing,
    out-of-order, or trailing section heading raises
    :class:`StagedVisualRemountError` with a clear message.

    Section text is the raw Markdown between the section heading and the next
    heading, so manuscript prose is preserved byte-for-byte.
    """

    if not isinstance(markdown, str) or not markdown.strip():
        raise StagedVisualRemountError(
            "staged manuscript markdown is empty"
        )
    lines = markdown.splitlines()
    headings: list[dict[str, Any]] = []
    for index, line in enumerate(lines):
        match = _HEADING_RE.match(line)
        if not match:
            continue
        headings.append(
            {
                "line": index + 1,
                "level": len(match.group("level")),
                "title": _normalize_heading(match.group("title")),
            }
        )
    if not headings:
        raise StagedVisualRemountError(
            "staged manuscript contains no ATX headings; expected "
            "Abstract, Introduction, S01..S08, Conclusion"
        )

    # Merge consecutive same-title headings at different levels
    # (``## Title`` + ``# Title``) into one section heading; the last
    # occurrence owns the section start.  Same-level repeats stay separate
    # so a genuine duplicate section heading is rejected below.
    unique: list[dict[str, Any]] = []
    for heading in headings:
        if unique and (
            _normalize_heading(unique[-1]["title"]).casefold()
            == heading["title"].casefold()
            and unique[-1]["level"] != heading["level"]
        ):
            unique[-1]["toc_duplicate"] = True
            unique[-1]["toc_duplicate_line"] = heading["line"]
            continue
        unique.append(
            {
                "line": heading["line"],
                "level": heading["level"],
                "title": heading["title"],
                "toc_duplicate": False,
                "toc_duplicate_line": None,
            }
        )

    if allow_dynamic_sections:
        if len(unique) < 4:
            raise StagedVisualRemountError(
                "dynamic staged manuscript requires Abstract, Introduction, "
                "at least one body section, and Conclusion"
            )
        first_id = _heading_explicit_id(unique[0]["title"])
        second_id = _heading_explicit_id(unique[1]["title"])
        last_id = _heading_explicit_id(unique[-1]["title"])
        if first_id != "Abstract" or second_id != "Introduction":
            raise StagedVisualRemountError(
                "dynamic staged manuscript must begin with Abstract and "
                "Introduction"
            )
        if last_id != "Conclusion":
            raise StagedVisualRemountError(
                "dynamic staged manuscript must end with Conclusion"
            )
        body_ids: list[str] = []
        explicit_numbers: list[int] = []
        for body_index, heading in enumerate(unique[2:-1], 1):
            explicit = _heading_explicit_id(heading["title"])
            section_id = explicit or f"S{body_index:02d}"
            if section_id in body_ids:
                raise StagedVisualRemountError(
                    f"duplicate section id '{section_id}' at line "
                    f"{heading['line']}"
                )
            body_ids.append(section_id)
            if explicit:
                try:
                    explicit_numbers.append(int(section_id[1:]))
                except ValueError:
                    raise StagedVisualRemountError(
                        f"invalid dynamic section id '{section_id}'"
                    ) from None
        if explicit_numbers != sorted(explicit_numbers):
            raise StagedVisualRemountError(
                "dynamic section ids are out of order: "
                + ", ".join(body_ids)
            )
        expected = ["Abstract", "Introduction", *body_ids, "Conclusion"]
    else:
        expected = list(STAGED_SECTION_IDS)
    sections: list[dict[str, Any]] = []
    consumed: set[str] = set()
    pointer = 0
    for index, heading in enumerate(unique):
        if pointer >= len(expected):
            raise StagedVisualRemountError(
                "unexpected heading at line "
                f"{heading['line']}: '{heading['title']}' (all canonical "
                f"sections {', '.join(STAGED_SECTION_IDS)} already seen)"
            )
        expected_id = expected[pointer]
        explicit = _heading_explicit_id(heading["title"])
        if explicit is not None:
            if explicit in consumed:
                raise StagedVisualRemountError(
                    f"duplicate section id '{explicit}' at line "
                    f"{heading['line']} (expected '{expected_id}')"
                )
            if explicit != expected_id:
                raise StagedVisualRemountError(
                    f"out-of-order section id '{explicit}' at line "
                    f"{heading['line']} (expected '{expected_id}')"
                )
        section_id = expected_id
        consumed.add(section_id)
        start = int(
            heading.get("toc_duplicate_line") or heading["line"]
        )  # content starts after the effective heading line
        end = (
            int(unique[index + 1]["line"]) - 1
            if index + 1 < len(unique)
            else len(lines)
        )
        text = "\n".join(lines[start:end]).strip()
        sections.append(
            {
                "section_id": section_id,
                "position": pointer,
                "title": (
                    heading["title"]
                    if section_id.startswith("S")
                    else section_id
                ),
                "heading_level": heading["level"],
                "heading_line": heading["line"],
                "toc_duplicate": heading["toc_duplicate"],
                "toc_duplicate_line": heading["toc_duplicate_line"],
                "text": text,
                "word_count": len(text.split()),
                "sha256": _sha256_text(text),
                "citation_ids": _citation_ids_from_text(text),
            }
        )
        pointer += 1

    if pointer < len(expected):
        missing = ", ".join(expected[pointer:])
        raise StagedVisualRemountError(
            f"missing section id(s) in staged manuscript: {missing}"
        )

    return {
        "schema_version": SCHEMA_VERSION,
        "manuscript_sha256": _sha256_text(markdown),
        "section_ids": [section["section_id"] for section in sections],
        "sections": sections,
        "toc_duplicate_heading_count": sum(
            1 for section in sections if section["toc_duplicate"]
        ),
    }


def _mapping(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else {}


def _text(value: Any) -> str:
    return " ".join(str(value or "").split())


def _list_of_mappings(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        return []
    return [
        _mapping(item)
        for item in value
        if isinstance(item, Mapping)
    ]


def _load_json_mapping(path: Path, label: str) -> dict[str, Any]:
    if not Path(path).is_file():
        raise StagedVisualRemountError(f"{label} not found: {path}")
    try:
        payload = json.loads(
            Path(path).read_text(encoding="utf-8", errors="replace")
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        raise StagedVisualRemountError(
            f"cannot read {label} {path}: {exc}"
        ) from exc
    if not isinstance(payload, Mapping):
        raise StagedVisualRemountError(
            f"{label} must be a JSON object: {path}"
        )
    return dict(payload)


def build_commander_enrichment(
    *,
    parsed: Mapping[str, Any],
    commander_work_order: Optional[Mapping[str, Any]] = None,
    staged_global_inputs: Optional[Mapping[str, Any]] = None,
) -> dict[str, Any]:
    """Build per-section enrichment from commander and staged inputs.

    Commander responsibilities/theses come from ``section_decisions``,
    ``proposed_section_order``, ``structure_gaps``,
    ``cross_section_conflicts``, and ``visual_work_orders``.  When the staged
    global inputs are provided, section-level thesis/reader/terminology
    context is merged in; front/back matter receives the article-level
    thesis/strategy context.
    """

    commander = _mapping(commander_work_order)
    global_inputs = _mapping(staged_global_inputs)
    global_sections = {
        str(_mapping(section).get("section_id")): _mapping(section)
        for section in _list_of_mappings(global_inputs.get("sections"))
        if _text(_mapping(section).get("section_id"))
    }
    decisions = {
        str(_mapping(row).get("section_id")): _mapping(row)
        for row in _list_of_mappings(commander.get("section_decisions"))
        if _text(_mapping(row).get("section_id"))
    }
    order_reasons = {
        str(_mapping(row).get("section_id")): _mapping(row)
        for row in _list_of_mappings(commander.get("proposed_section_order"))
        if _text(_mapping(row).get("section_id"))
    }
    structure_gaps: dict[str, list[dict[str, Any]]] = {}
    for row in _list_of_mappings(commander.get("structure_gaps")):
        section_id = _text(row.get("section_id"))
        if section_id:
            structure_gaps.setdefault(section_id, []).append(row)
    cross_section_conflicts: dict[str, list[dict[str, Any]]] = {}
    for row in _list_of_mappings(commander.get("cross_section_conflicts")):
        for section_id in row.get("sections") or []:
            sid = _text(section_id)
            if sid:
                cross_section_conflicts.setdefault(sid, []).append(row)
    visual_work_orders: dict[str, list[dict[str, Any]]] = {}
    for row in _list_of_mappings(commander.get("visual_work_orders")):
        for section_id in row.get("section_ids") or (
            [row.get("section_id")] if row.get("section_id") else []
        ):
            sid = _text(section_id)
            if sid:
                visual_work_orders.setdefault(sid, []).append(row)

    global_context = {
        "user_question": _text(global_inputs.get("user_question")),
        "problem_understanding": _text(
            global_inputs.get("problem_understanding")
        ),
        "global_review_thesis": _text(
            global_inputs.get("global_review_thesis")
        ),
        "global_narrative_strategy": _text(
            global_inputs.get("global_narrative_strategy")
        ),
    }
    per_section: dict[str, dict[str, Any]] = {}
    for section in _list_of_mappings(parsed.get("sections")):
        section_id = _text(section.get("section_id"))
        if not section_id:
            continue
        staged = global_sections.get(section_id, {})
        narrative = _mapping(staged.get("narrative_strategy"))
        if section_id.startswith("S"):
            base = {
                "commander_decision": _text(
                    decisions.get(section_id, {}).get("decision")
                ),
                "commander_rationale": _text(
                    decisions.get(section_id, {}).get("rationale")
                ),
                "commander_order_reason": _text(
                    order_reasons.get(section_id, {}).get("reason")
                ),
                "commander_structure_gaps": structure_gaps.get(
                    section_id, []
                ),
                "commander_cross_section_conflicts": (
                    cross_section_conflicts.get(section_id, [])
                ),
                "commander_visual_work_orders": visual_work_orders.get(
                    section_id, []
                ),
                "chapter_thesis": _text(
                    staged.get("chapter_thesis")
                    or staged.get("central_thesis")
                ),
                "central_thesis": _text(staged.get("central_thesis")),
                "reader_takeaway": _text(staged.get("reader_takeaway")),
                "narrative_strategy": _text(
                    narrative.get("statement")
                    or staged.get("narrative_strategy")
                ),
                "terminology": staged.get("terminology", []),
                "review_summary": _mapping(staged.get("review_summary")),
                "core_trust_boundary": _text(
                    staged.get("core_trust_boundary")
                ),
                "explanatory_trust_boundary": _text(
                    staged.get("explanatory_trust_boundary")
                ),
                "argument_sequence": _list_of_mappings(
                    staged.get("argument_sequence")
                ),
            }
            base.update(global_context)
        else:
            base = {
                "commander_decision": "",
                "commander_rationale": "",
                "commander_order_reason": "",
                "commander_structure_gaps": [],
                "commander_cross_section_conflicts": [],
                "commander_visual_work_orders": [],
                "chapter_thesis": "",
                "central_thesis": "",
                "reader_takeaway": "",
                "narrative_strategy": "",
                "terminology": [],
                "review_summary": {},
                "core_trust_boundary": "",
                "explanatory_trust_boundary": "",
                "argument_sequence": [],
                **global_context,
            }
        per_section[section_id] = base

    return {
        "schema_version": f"{SCHEMA_VERSION}.enrichment.v1",
        "commander_fingerprint": _text(commander.get("fingerprint")),
        "commander_manuscript_diagnosis": _text(
            commander.get("manuscript_diagnosis")
        ),
        "commander_visual_work_orders": _list_of_mappings(
            commander.get("visual_work_orders")
        ),
        "global": global_context,
        "sections": per_section,
    }


def _claims_from_enrichment(
    section: Mapping[str, Any],
    enrichment: Mapping[str, Any],
) -> tuple[list[dict[str, Any]], bool]:
    """Build planner claim inputs from available argument step handles."""

    claims: list[dict[str, Any]] = []
    seen: set[str] = set()
    proxy_statements = False
    citation_ids = [
        _text(item)
        for item in (section.get("citation_ids") or [])
        if _text(item)
    ]
    for step in _list_of_mappings(enrichment.get("argument_sequence")):
        purpose = _text(step.get("purpose"))
        if purpose:
            proxy_statements = True
        for handle in step.get("claim_handles") or []:
            claim_id = _text(handle)
            if not claim_id or claim_id in seen:
                continue
            seen.add(claim_id)
            claims.append(
                {
                    "claim_id": claim_id,
                    "statement": purpose,
                    "status": "approved",
                    "citation_ids": list(citation_ids),
                }
            )
    return claims, proxy_statements


def build_planner_section_inputs(
    *,
    parsed: Mapping[str, Any],
    enrichment: Mapping[str, Any],
) -> list[dict[str, Any]]:
    """Build rich planner section inputs from parsed manuscript + enrichment."""

    per_section = _mapping(enrichment.get("sections"))
    section_inputs: list[dict[str, Any]] = []
    for section in _list_of_mappings(parsed.get("sections")):
        section_id = _text(section.get("section_id"))
        en = _mapping(per_section.get(section_id))
        role_parts: list[str] = []
        decision = _text(en.get("commander_decision"))
        rationale = _text(en.get("commander_rationale"))
        if decision:
            role_parts.append(f"commander:{decision}")
        if rationale:
            role_parts.append(rationale)
        for key in (
            "chapter_thesis",
            "reader_takeaway",
            "narrative_strategy",
            "global_review_thesis",
            "global_narrative_strategy",
        ):
            value = _text(en.get(key))
            if value:
                role_parts.append(value)
        claims, proxy_statements = _claims_from_enrichment(section, en)
        citation_ids = [
            _text(item)
            for item in (section.get("citation_ids") or [])
            if _text(item)
        ]
        citations = [
            {
                "citation_id": citation_id,
                "paper_id": citation_id,
                "doi": (
                    citation_id
                    if citation_id.lower().startswith("doi:")
                    else ""
                ),
                "text": "",
            }
            for citation_id in citation_ids
        ]
        section_inputs.append(
            {
                "section_id": section_id,
                "title": _text(section.get("title")),
                "text": str(section.get("text") or ""),
                "argument_role": " | ".join(
                    dict.fromkeys(part for part in role_parts if part)
                ),
                "claims": claims,
                "citations": citations,
                "expected_visual_arguments": [],
                "claim_statement_proxy": proxy_statements,
            }
        )
    return section_inputs


def build_factory_blueprint(
    *,
    parsed: Mapping[str, Any],
    enrichment: Mapping[str, Any],
    section_inputs: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Build the portable factory blueprint with full section context.

    The blueprint is deterministic and relocatable; the factory consumes it
    through the existing ``--blueprint`` contract.  Each top-level section
    carries ``section_id``, ``title``, the full section text, the rich
    ``argument_role``, and the citation identities so the source-figure
    vision audit is judged against the actual target section.
    """

    role_by_id = {
        str(section.get("section_id") or ""): str(
            section.get("argument_role") or ""
        )
        for section in section_inputs
    }
    global_context = _mapping(enrichment.get("global"))
    sections: list[dict[str, Any]] = []
    for section in _list_of_mappings(parsed.get("sections")):
        section_id = _text(section.get("section_id"))
        if not section_id:
            continue
        sections.append(
            {
                "section_id": section_id,
                "position": int(section.get("position") or 0),
                "title": _text(section.get("title")),
                "full_text": str(section.get("text") or ""),
                "argument_role": role_by_id.get(section_id, ""),
                "citation_ids": [
                    _text(item)
                    for item in (section.get("citation_ids") or [])
                    if _text(item)
                ],
            }
        )
    return {
        "schema_version": f"{SCHEMA_VERSION}.blueprint.v1",
        "review_thesis": _text(
            global_context.get("global_review_thesis")
            or enrichment.get("commander_manuscript_diagnosis")
        ),
        "sections": sections,
    }


def _resolve_path(
    path: Optional[Path],
    project_root: Path,
    label: str,
) -> Optional[Path]:
    if path is None:
        return None
    candidate = Path(path)
    if not candidate.is_absolute():
        candidate = project_root / candidate
    return candidate.resolve()


def _display_path(path: Path, project_root: Path) -> str:
    """Return a path relative to the project root when possible."""

    resolved = Path(path).resolve()
    try:
        return str(resolved.relative_to(project_root))
    except ValueError:
        return str(resolved)


def _relative_path_string(
    value: Any,
    project_root: Path,
    cache_root: Optional[Path] = None,
) -> str:
    """Rebase an absolute path to cache-root, then project-root, relative."""

    if not isinstance(value, str) or not value.strip():
        return str(value) if value is not None else ""
    path = Path(value)
    if not path.is_absolute():
        return value
    try:
        resolved = path.resolve()
        for anchor in (cache_root, project_root):
            if anchor is None:
                continue
            try:
                return str(resolved.relative_to(anchor))
            except ValueError:
                continue
        return value
    except (OSError, ValueError):
        return value


def _normalize_plan_paths(
    value: Any,
    project_root: Path,
    cache_root: Optional[Path] = None,
) -> Any:
    """Deep-copy plan data with absolute image paths made project-relative.

    Every absolute path string (placement image paths, ``source_map``
    resource refs, ``path_key`` values) is rebased to the cache root first
    and then the project root; relative strings, captions, ids, scores, and
    non-path text are preserved verbatim so the copy remains faithful to the
    planner output while being relocatable.
    """

    if isinstance(value, Mapping):
        return {
            key: _normalize_plan_paths(item, project_root, cache_root)
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [
            _normalize_plan_paths(item, project_root, cache_root)
            for item in value
        ]
    if isinstance(value, str):
        return _relative_path_string(value, project_root, cache_root)
    return value


def _remount_plan_copy(
    plan: Mapping[str, Any],
    *,
    content_fingerprint: str,
    project_root: Path,
    cache_root: Path,
) -> dict[str, Any]:
    """Deterministic, relocatable bridge copy of the planner construction plan.

    The raw planner plan (with absolute image paths and its own
    path-dependent ``input_fingerprint``) stays under ``planner/`` for the
    factory; this copy is the bridge's auditable view and is byte-identical
    for identical manuscript/cache content regardless of output or cache
    location.
    """

    plan_copy = _normalize_plan_paths(plan, project_root, cache_root)
    plan_copy = dict(plan_copy)
    plan_copy["schema_version"] = f"{SCHEMA_VERSION}.plan.v1"
    plan_copy["content_fingerprint"] = content_fingerprint
    plan_copy.pop("input_fingerprint", None)
    editorial = plan_copy.get("visual_editorial_plan")
    if isinstance(editorial, dict):
        editorial.pop("input_fingerprint", None)
    return plan_copy


def visual_cache_content_sha256(
    records: Sequence[Mapping[str, Any]],
) -> str:
    """Relocation-safe content hash of loaded visual cache records.

    Absolute image paths, source file paths, and other location-dependent
    fields are excluded so the same snapshot content hashes identically from
    any checkout location.
    """

    normalized: list[dict[str, Any]] = []
    for record in records:
        row = _mapping(record)
        normalized.append(
            {
                key: value
                for key, value in row.items()
                if "path" not in key.casefold()
                and key
                not in {
                    "cache_format",
                    "image_origin",
                    "remote_image_url",
                    "source_file",
                    "source_route",
                    "source_url",
                }
            }
        )
    normalized.sort(
        key=lambda item: (
            _text(item.get("chunk_id") or item.get("unit_id") or "")
        )
    )
    return _sha256_json(
        {
            "schema_version": f"{SCHEMA_VERSION}.cache_content.v1",
            "records": normalized,
        }
    )


def _planner_config(
    max_placements_per_section: int,
    allow_generation_requests: bool,
) -> ArticleVisualAssetPlannerConfig:
    return ArticleVisualAssetPlannerConfig(
        max_placements_per_section=max_placements_per_section,
        max_generation_requests_per_section=(
            1 if allow_generation_requests else 0
        ),
        max_total_visual_items_per_section=(
            max_placements_per_section
            + (1 if allow_generation_requests else 0)
        ),
    )


def _permission_summary(placement: Mapping[str, Any]) -> dict[str, Any]:
    permission = _mapping(placement.get("permission"))
    return {
        "status": _text(permission.get("status")),
        "license": _text(permission.get("license")),
        "use_permission": _text(permission.get("use_permission")),
        "note": _text(permission.get("note")),
    }


def build_remount_audit(
    *,
    plan: Mapping[str, Any],
    parsed: Mapping[str, Any],
    enrichment: Mapping[str, Any],
    config: Mapping[str, Any],
    fingerprints: Mapping[str, Any],
    provenance: Mapping[str, Any],
    project_root: Path,
    cache_root: Path,
    run_id: str,
) -> dict[str, Any]:
    """Build the deterministic remount audit from plan + inputs."""

    section_plans = {
        str(_mapping(item).get("section_id")): _mapping(item)
        for item in _list_of_mappings(plan.get("sections"))
    }
    placements = _list_of_mappings(plan.get("placements"))
    unfilled = _list_of_mappings(plan.get("unfilled_visual_needs"))
    sections: list[dict[str, Any]] = []
    weak_fallback_count = 0
    placement_permission_counts: dict[str, int] = {}
    publication_eligible = 0
    publication_ineligible = 0
    for section in _list_of_mappings(parsed.get("sections")):
        section_id = _text(section.get("section_id"))
        section_plan = _mapping(section_plans.get(section_id))
        section_placements = _list_of_mappings(
            section_plan.get("placements")
        )
        section_unfilled = _list_of_mappings(
            section_plan.get("unfilled_needs")
        )
        placement_summaries: list[dict[str, Any]] = []
        for placement in section_placements:
            is_weak_fallback = (
                str(placement.get("status"))
                == "traceable_source_pending_review"
                and str(placement.get("review_required_reason"))
                == "fail_open_weak_or_pending_only_relevant_candidate"
            )
            if is_weak_fallback:
                weak_fallback_count += 1
            permission = _permission_summary(placement)
            permission_status = permission["status"] or "unknown"
            placement_permission_counts[permission_status] = (
                placement_permission_counts.get(permission_status, 0) + 1
            )
            if bool(placement.get("publication_eligible")):
                publication_eligible += 1
            else:
                publication_ineligible += 1
            placement_summaries.append(
                {
                    "placement_id": _text(placement.get("placement_id")),
                    "visual_chunk_id": _text(
                        placement.get("visual_chunk_id")
                    ),
                    "paper_id": _text(placement.get("paper_id")),
                    "local_image_path": _text(
                        _relative_path_string(
                            placement.get("local_image_path"),
                            project_root,
                            cache_root=cache_root,
                        )
                    ),
                    "status": _text(placement.get("status")),
                    "review_state": _text(placement.get("review_state")),
                    "image_review_required": bool(
                        placement.get("image_review_required")
                    ),
                    "permission": permission,
                    "publication_eligible": bool(
                        placement.get("publication_eligible")
                    ),
                    "publication_eligible_reason": _text(
                        placement.get("publication_eligible_reason")
                    ),
                }
            )
        placement_count = len(section_placements)
        coverage_status = (
            "placed"
            if placement_count > 0
            else (
                "weak_fallback"
                if any(
                    str(item.get("reason"))
                    == "fail_open_weak_or_pending_only_relevant_candidate"
                    for item in section_unfilled
                )
                else "empty_recorded"
            )
        )
        sections.append(
            {
                "section_id": section_id,
                "title": _text(section.get("title")),
                "position": int(section.get("position") or 0),
                "word_count": int(section.get("word_count") or 0),
                "heading_line": int(section.get("heading_line") or 0),
                "toc_duplicate": bool(section.get("toc_duplicate")),
                "citation_count": len(
                    section.get("citation_ids") or []
                ),
                "claim_count": int(
                    section_plan.get("approved_claim_count") or 0
                ),
                "placement_count": placement_count,
                "capacity": int(
                    config.get("max_placements_per_section") or 0
                ),
                "coverage_status": coverage_status,
                "placements": placement_summaries,
                "unfilled_needs": [
                    {
                        "need_id": _text(item.get("need_id")),
                        "need_kind": _text(item.get("need_kind")),
                        "reason": _text(item.get("reason")),
                        "status": _text(item.get("status")),
                        "argumentative_purpose": _text(
                            item.get("argumentative_purpose")
                        ),
                    }
                    for item in section_unfilled
                ],
            }
        )

    empty_sections = [
        section["section_id"]
        for section in sections
        if section["placement_count"] == 0
    ]
    validation = _mapping(plan.get("validation"))
    return {
        "schema_version": SCHEMA_VERSION,
        "run_id": run_id or "default",
        "mode": "staged_manuscript_to_visual_planner_bridge",
        "inputs": {
            "manuscript_path": _text(provenance.get("manuscript_path")),
            "manuscript_sha256": _text(parsed.get("manuscript_sha256")),
            "commander_work_order_path": _text(
                provenance.get("commander_work_order_path")
            ),
            "commander_fingerprint": _text(
                enrichment.get("commander_fingerprint")
            ),
            "commander_visual_work_orders": len(
                _list_of_mappings(
                    enrichment.get("commander_visual_work_orders")
                )
            ),
            "staged_global_inputs_path": _text(
                provenance.get("staged_global_inputs_path")
            ),
            "visual_cache_path": _text(provenance.get("visual_cache_path")),
        },
        "fingerprints": dict(fingerprints),
        "sections": sections,
        "coverage": {
            "section_count": len(sections),
            "sections_with_placements": len(sections)
            - len(empty_sections),
            "sections_without_placements": empty_sections,
            "total_placements": len(placements),
            "max_placements_per_section": int(
                config.get("max_placements_per_section") or 0
            ),
            "weak_fallback_placements": weak_fallback_count,
            "unfilled_need_count": len(unfilled),
            "empty_coverage_recorded": bool(empty_sections),
            "generation_requests_emitted": bool(
                plan.get("conceptual_figure_requests")
            ),
            "images_generated_by_bridge": False,
            "structural_visual_policy": {
                "abstract_conclusion_zero": True,
                "introduction_cap_one": True,
                "excluded_by_policy": sum(
                    1
                    for item in unfilled
                    if str(item.get("reason") or "").startswith(
                        "excluded_structural_policy_"
                    )
                ),
            },
        },
        "permission_publication": {
            "placements_by_permission_status": {
                key: placement_permission_counts[key]
                for key in sorted(placement_permission_counts)
            },
            "publication_eligible_placements": publication_eligible,
            "publication_ineligible_placements": publication_ineligible,
            "policy": (
                "source images remain internal-study/publication-ineligible "
                "unless permission explicitly allows"
            ),
        },
        "planner": {
            "role": "article_visual_asset_planner.deterministic_sidecar",
            "validation_status": _text(validation.get("status")),
            "errors": validation.get("errors") or [],
            "warnings": validation.get("warnings") or [],
            "fail_open": bool(validation.get("fail_open")),
            "output_subdir": PLANNER_SUBDIR,
        },
        "policy": {
            "latest_manuscript_authoritative": True,
            "no_prose_rewrites": True,
            "no_new_images_generated": True,
            "source_cache_unmodified": True,
            "old_plans_unmodified": True,
            "fail_open_for_missing_visuals": True,
        },
        "artifacts": {
            "inputs": ARTIFACT_INPUTS,
            "plan": ARTIFACT_PLAN,
            "review_queue": ARTIFACT_REVIEW_QUEUE,
            "factory_plan": ARTIFACT_FACTORY_PLAN,
            "audit": ARTIFACT_AUDIT,
            "blueprint": ARTIFACT_BLUEPRINT,
            "planner_construction_plan": (
                f"{PLANNER_SUBDIR}/VISUAL_CONSTRUCTION_PLAN.json"
            ),
            "planner_editorial_plan": (
                f"{PLANNER_SUBDIR}/VISUAL_EDITORIAL_PLAN.json"
            ),
            "planner_image_review_queue": (
                f"{PLANNER_SUBDIR}/ARTICLE_VISUAL_IMAGE_REVIEW_QUEUE.json"
            ),
        },
    }


def build_remount_input_fingerprint(
    *,
    parsed: Mapping[str, Any],
    enrichment: Mapping[str, Any],
    section_inputs: Sequence[Mapping[str, Any]],
    config: Mapping[str, Any],
    visual_cache_content_sha256: str = "",
    factory_blueprint_sha256: str = "",
    structural_visual_policy_enabled: bool = True,
) -> str:
    """Relocation-safe fingerprint for every remount input that affects output.

    Manuscript text, enrichment, planner section inputs, config, and the
    visual-cache content hash are included; no output or cache paths are.
    """

    payload = {
        "schema_version": f"{SCHEMA_VERSION}.input_fingerprint.v1",
        "parsed_manuscript": parsed,
        "enrichment": enrichment,
        "section_inputs": [
            {
                key: value
                for key, value in dict(section).items()
                if key != "claim_statement_proxy"
            }
            for section in section_inputs
        ],
        "config": config,
        "visual_cache_content_sha256": visual_cache_content_sha256,
        "factory_blueprint_sha256": factory_blueprint_sha256,
        "structural_visual_policy_enabled": bool(
            structural_visual_policy_enabled
        ),
    }
    return _sha256_json(payload)


def _planner_factory_plan_reference(
    *,
    plan: Mapping[str, Any],
    content_fingerprint: str,
    project_root: Path,
    cache_root: Path,
) -> dict[str, Any]:
    """Optional factory-ready plan reference (editorial plan + pointers)."""

    editorial = _mapping(plan.get("visual_editorial_plan"))
    editorial = _normalize_plan_paths(
        editorial,
        project_root,
        cache_root,
    )
    editorial.pop("input_fingerprint", None)
    return {
        "schema_version": f"{SCHEMA_VERSION}.factory_plan_reference.v1",
        "content_fingerprint": content_fingerprint,
        "editorial_plan": editorial,
        "factory_targets": {
            "blueprint_path": ARTIFACT_BLUEPRINT,
            "visual_editorial_plan_path": (
                f"{PLANNER_SUBDIR}/VISUAL_EDITORIAL_PLAN.json"
            ),
            "construction_plan_path": (
                f"{PLANNER_SUBDIR}/VISUAL_CONSTRUCTION_PLAN.json"
            ),
            "image_review_queue_path": (
                f"{PLANNER_SUBDIR}/ARTICLE_VISUAL_IMAGE_REVIEW_QUEUE.json"
            ),
        },
        "generation_policy": {
            "generation_requests_emitted": bool(
                editorial.get("conceptual_figure_requests")
            ),
            "images_generated_by_bridge": False,
            "note": (
                "This bridge only plans; the visual evidence factory must "
                "be invoked separately and never without explicit approval."
            ),
        },
        "structural_visual_policy": {
            "abstract_conclusion_zero": True,
            "introduction_cap_one": True,
            "note": (
                "The factory applies the same structural policy at "
                "materialization time; the raw planner files under "
                "planner/ may still list front/back-matter candidates."
            ),
        },
        "audit_reference": ARTIFACT_AUDIT,
    }


def run_staged_visual_remount(
    *,
    manuscript_path: Path,
    visual_cache_path: Path,
    output_dir: Path,
    commander_work_order_path: Optional[Path] = None,
    staged_global_inputs_path: Optional[Path] = None,
    project_root: Optional[Path] = None,
    run_id: str = "",
    max_placements_per_section: int = 2,
    allow_generation_requests: bool = False,
) -> dict[str, Any]:
    """Run the staged-manuscript-to-visual-planner remount bridge.

    Reads the staged complete manuscript Markdown (plus optional commander
    work order / staged global inputs), reruns the existing
    ``run_article_visual_asset_planner`` against the supplied long-term
    visual cache snapshot, and writes deterministic remount artifacts into
    ``output_dir``.  No source caches or old plans are modified and no image
    generation is executed.
    """

    if max_placements_per_section not in {0, 1, 2}:
        raise StagedVisualRemountError(
            "max_placements_per_section must be 0, 1, or 2; got "
            f"{max_placements_per_section!r}"
        )
    root = Path(project_root or Path(__file__).resolve().parents[2])
    root = root.resolve()
    manuscript = _resolve_path(
        manuscript_path, root, "manuscript_path"
    )
    cache = _resolve_path(visual_cache_path, root, "visual_cache_path")
    commander_path = _resolve_path(
        commander_work_order_path, root, "commander_work_order_path"
    )
    global_inputs_path = _resolve_path(
        staged_global_inputs_path, root, "staged_global_inputs_path"
    )
    if manuscript is None:
        raise StagedVisualRemountError("manuscript_path is required")
    if cache is None:
        raise StagedVisualRemountError("visual_cache_path is required")
    if not manuscript.is_file():
        raise StagedVisualRemountError(
            f"staged manuscript not found: {manuscript}"
        )
    if not cache.exists():
        raise StagedVisualRemountError(
            f"visual cache snapshot not found: {cache}"
        )

    try:
        markdown = manuscript.read_text(
            encoding="utf-8",
            errors="replace",
        )
    except OSError as exc:
        raise StagedVisualRemountError(
            f"cannot read staged manuscript {manuscript}: {exc}"
        ) from exc

    parsed = parse_staged_manuscript(
        markdown,
        allow_dynamic_sections=True,
    )
    commander_payload = (
        _load_json_mapping(commander_path, "commander work order")
        if commander_path is not None
        else None
    )
    global_inputs_payload = (
        _load_json_mapping(global_inputs_path, "staged global inputs")
        if global_inputs_path is not None
        else None
    )
    enrichment = build_commander_enrichment(
        parsed=parsed,
        commander_work_order=commander_payload,
        staged_global_inputs=global_inputs_payload,
    )
    section_inputs = build_planner_section_inputs(
        parsed=parsed,
        enrichment=enrichment,
    )
    factory_blueprint = build_factory_blueprint(
        parsed=parsed,
        enrichment=enrichment,
        section_inputs=section_inputs,
    )
    factory_blueprint_sha256 = _sha256_json(factory_blueprint)
    config = {
        "max_placements_per_section": int(max_placements_per_section),
        "allow_generation_requests": bool(allow_generation_requests),
        "structural_visual_policy_enabled": True,
    }

    target = Path(output_dir).resolve()
    planner_output = target / PLANNER_SUBDIR
    plan = run_article_visual_asset_planner(
        sections=[dict(section) for section in section_inputs],
        visual_cache_paths=[cache],
        output_dir=planner_output,
        config=_planner_config(
            max_placements_per_section=max_placements_per_section,
            allow_generation_requests=allow_generation_requests,
        ),
    )
    plan = apply_structural_visual_policy(plan)
    plan["visual_editorial_plan"] = to_visual_editorial_plan(plan)
    records_loaded = 0
    records: list[dict[str, Any]] = []
    cache_load_error = ""
    try:
        records = load_visual_cache_records(cache)
        records_loaded = len(records)
    except Exception as exc:
        cache_load_error = (
            f"{type(exc).__name__}:{exc}"
        )
    cache_content_sha256 = visual_cache_content_sha256(records)
    remount_fingerprint = build_remount_input_fingerprint(
        parsed=parsed,
        enrichment=enrichment,
        section_inputs=section_inputs,
        config=config,
        visual_cache_content_sha256=cache_content_sha256,
        factory_blueprint_sha256=factory_blueprint_sha256,
        structural_visual_policy_enabled=True,
    )
    fingerprints = {
        "remount_input_fingerprint": remount_fingerprint,
        "factory_blueprint_sha256": factory_blueprint_sha256,
        "structural_visual_policy": (
            "abstract_conclusion_zero_introduction_cap_one"
        ),
        "manuscript_sha256": _text(parsed.get("manuscript_sha256")),
        "commander_sha256": (
            _sha256_json(commander_payload)
            if commander_payload is not None
            else ""
        ),
        "staged_global_inputs_sha256": (
            _sha256_json(global_inputs_payload)
            if global_inputs_payload is not None
            else ""
        ),
        "visual_cache_content_sha256": cache_content_sha256,
        "visual_cache_records_loaded": records_loaded,
        "visual_cache_load_error": cache_load_error,
    }
    provenance = {
        "manuscript_path": _display_path(manuscript, root),
        "commander_work_order_path": (
            _display_path(commander_path, root)
            if commander_path is not None
            else ""
        ),
        "staged_global_inputs_path": (
            _display_path(global_inputs_path, root)
            if global_inputs_path is not None
            else ""
        ),
        "visual_cache_path": _display_path(cache, root),
    }
    audit = build_remount_audit(
        plan=plan,
        parsed=parsed,
        enrichment=enrichment,
        config=config,
        fingerprints=fingerprints,
        provenance=provenance,
        project_root=root,
        cache_root=cache,
        run_id=run_id,
    )
    factory_reference = _planner_factory_plan_reference(
        plan=plan,
        content_fingerprint=remount_fingerprint,
        project_root=root,
        cache_root=cache,
    )
    plan_copy = _remount_plan_copy(
        plan,
        content_fingerprint=remount_fingerprint,
        project_root=root,
        cache_root=cache,
    )

    inputs_artifact = {
        "schema_version": f"{SCHEMA_VERSION}.inputs.v1",
        "run_id": run_id or "default",
        "parsed_manuscript": parsed,
        "enrichment": enrichment,
        "section_inputs": [dict(section) for section in section_inputs],
        "config": config,
        "fingerprints": fingerprints,
        "provenance": provenance,
        "factory_blueprint": factory_blueprint,
    }
    atomic_write_json(target / ARTIFACT_INPUTS, inputs_artifact)
    atomic_write_json(target / ARTIFACT_BLUEPRINT, factory_blueprint)
    atomic_write_json(target / ARTIFACT_PLAN, plan_copy)
    atomic_write_json(
        target / ARTIFACT_REVIEW_QUEUE,
        _normalize_plan_paths(
            _mapping(plan.get("image_review_queue")),
            root,
            cache,
        ),
    )
    atomic_write_json(target / ARTIFACT_FACTORY_PLAN, factory_reference)
    atomic_write_json(target / ARTIFACT_AUDIT, audit)

    return {
        "schema_version": SCHEMA_VERSION,
        "run_id": run_id or "default",
        "status": "completed",
        "output_dir": str(target),
        "manuscript_sha256": _text(parsed.get("manuscript_sha256")),
        "section_ids": parsed.get("section_ids") or [],
        "fingerprints": fingerprints,
        "provenance": provenance,
        "coverage": dict(audit.get("coverage") or {}),
        "planner_validation": {
            "status": _text(
                _mapping(plan.get("validation")).get("status")
            ),
            "errors": _mapping(plan.get("validation")).get("errors") or [],
        },
        "artifacts": {
            name: str(target / relative)
            for name, relative in (
                (
                    "inputs",
                    ARTIFACT_INPUTS,
                ),
                (
                    "plan",
                    ARTIFACT_PLAN,
                ),
                (
                    "review_queue",
                    ARTIFACT_REVIEW_QUEUE,
                ),
                (
                    "factory_plan",
                    ARTIFACT_FACTORY_PLAN,
                ),
                (
                    "audit",
                    ARTIFACT_AUDIT,
                ),
                (
                    "blueprint",
                    ARTIFACT_BLUEPRINT,
                ),
            )
        },
    }


__all__ = [
    "ARTIFACT_AUDIT",
    "ARTIFACT_BLUEPRINT",
    "ARTIFACT_FACTORY_PLAN",
    "ARTIFACT_INPUTS",
    "ARTIFACT_PLAN",
    "ARTIFACT_REVIEW_QUEUE",
    "PLANNER_SUBDIR",
    "SCHEMA_VERSION",
    "STAGED_SECTION_IDS",
    "StagedVisualRemountError",
    "build_commander_enrichment",
    "build_factory_blueprint",
    "build_planner_section_inputs",
    "build_remount_audit",
    "build_remount_input_fingerprint",
    "parse_staged_manuscript",
    "run_staged_visual_remount",
]
